apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  labels:
    type: nfs
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - resvport
    - nfsvers=4.0
  nfs:
    path: /volume2/nfs_edu/edu2
    server: shclub.synology.me
