apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim2
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mariadb-pv
